# Generated by Django 4.1.6 on 2023-02-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('inscricao', models.CharField(max_length=11, verbose_name='Inscrição Imobiliária')),
                ('utmX', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='UTM_X')),
                ('utmY', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='UTM_Y')),
                ('regiao', models.CharField(choices=[('anhanduizinho', 'Anhanduizinho'), ('bandeira', 'Bandeira'), ('centro', 'Centro'), ('imbirussu', 'Imbirussu'), ('lagoa', 'Lagoa'), ('prosa', 'Prosa'), ('segredo', 'Segredo'), ('dist_anhandui', 'Dist. Anhandui'), ('dist_rochedinho', 'Dist. Rochedinho'), ('zona_rural', 'Zona Rural')], max_length=16, verbose_name='Região')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('parcelamento', models.CharField(max_length=5, verbose_name='Parcelamento')),
                ('quadra', models.CharField(max_length=5, verbose_name='Quadra')),
                ('lote', models.CharField(max_length=5, verbose_name='Lote')),
                ('tipo_logradouro', models.CharField(choices=[('Avenida', 'Avenida'), ('Rua', 'Rua'), ('Travessa', 'Travessa'), ('Via', 'Via'), ('Rodovia', 'Rodovia'), ('Estrada', 'Estrada'), ('Chacara', 'Chacara')], max_length=25, verbose_name='Tipo Logradouro')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=6, verbose_name='Número')),
                ('observacao', models.TextField(verbose_name='Observação')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
