# Generated by Django 4.1.6 on 2023-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('inscricao', models.CharField(blank=True, help_text='Digite os 11 números', max_length=11, verbose_name='Inscrição Imobiliária')),
                ('utmX', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='UTM_X')),
                ('utmY', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='UTM_Y')),
                ('regiao', models.CharField(choices=[('Anhanduizinho', 'Anhanduizinho'), ('Bandeira', 'Bandeira'), ('Centro', 'Centro'), ('Imbirussu', 'Imbirussu'), ('Lagoa', 'Lagoa'), ('Prosa', 'Prosa'), ('Segredo', 'Segredo'), ('Dist_Anhandui', 'Dist. Anhandui'), ('Dist_Rochedinho', 'Dist. Rochedinho'), ('Zona_Rural', 'Zona Rural')], max_length=16, verbose_name='Região')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('parcelamento', models.CharField(max_length=5, verbose_name='Parcelamento')),
                ('quadra', models.CharField(max_length=5, verbose_name='Quadra')),
                ('lote', models.CharField(max_length=5, verbose_name='Lote')),
                ('tipo_logradouro', models.CharField(choices=[('Avenida', 'Avenida'), ('Rua', 'Rua'), ('Travessa', 'Travessa'), ('Via', 'Via'), ('Rodovia', 'Rodovia'), ('Estrada', 'Estrada'), ('Chacara', 'Chacara')], max_length=25, verbose_name='Tipo Logradouro')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=6, verbose_name='Número')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
    ]
