# Generated by Django 4.1.6 on 2023-02-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='inscricao',
            field=models.CharField(max_length=11, null=None, verbose_name='Inscrição Imobiliária'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='observacao',
            field=models.TextField(null=None, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='utmX',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=None, verbose_name='UTM_X'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='utmY',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=None, verbose_name='UTM_Y'),
        ),
    ]
