# Generated by Django 4.1.6 on 2023-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_localizacao_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='inscricao',
            field=models.CharField(blank=True, max_length=11, verbose_name='Inscrição Imobiliária'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='observacao',
            field=models.TextField(verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='utmX',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='UTM_X'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='utmY',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='UTM_Y'),
        ),
    ]
