# Generated by Django 4.1.6 on 2023-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_localizacao_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='inscricao',
            field=models.CharField(blank=True, help_text='Digite os 11 números', max_length=11, verbose_name='Inscrição Imobiliária'),
        ),
    ]
