# Generated by Django 4.1.6 on 2023-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_localizacao_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='utmX',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='UTM_X'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='utmY',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='UTM_Y'),
        ),
    ]
