# Generated by Django 4.1.6 on 2023-02-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_localizacao_utmx_alter_localizacao_utmy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localizacao',
            options={'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações'},
        ),
    ]
